# Generated by Django 5.2.7 on 2025-12-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_remove_listing_address_listing_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="is_rented",
            field=models.BooleanField(default=False),
        ),
    ]
